name: Run tests

env:
  RUBY_VERSION: 2.6.3
  POSTGRES_USER: a_blog
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: postgres

on: [push,pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          bundler exec rails db:setup RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake